
main: *.cpp
	g++ -fopenmp -O2 -I /scratch/dpmunro/eigen/for_hpc/eigen-3.4.0 -I /scratch/dpmunro/eigen/for_hpc/json -I /scratch/dpmunro/eigen/topopt_is/LBFGSB/ main.cpp read_json.cpp wrte_lvtk.cpp dmat.cpp smat.cpp scg.cpp filt_init.cpp assy.cpp solv.cpp sens.cpp duqp.cpp -o main
