
main: *.cpp
	g++ -fopenmp -O2 -I /home/dirk/adv_fem/eigen/eigen-3.4.0 -I /home/dirk/adv_fem/eigen/json -I /home/dirk/adv_fem/3igen/topopt/LBFGSB/ main.cpp read_json.cpp wrte_lvtk.cpp dmat.cpp smat.cpp scg.cpp filt_init.cpp assy.cpp solv.cpp sens.cpp duqp.cpp -o main
